#!/usr/bin/env ruby
# generate_chain_lut.rb — Bake multiple preset pipelines into a single .cube LUT
#
# Usage:
#   ruby generate_chain_lut.rb <output_path> <preset1>@<strength> <preset2>@<strength> ...
#
# Example:
#   ruby generate_chain_lut.rb correction_luts/studio_dance.cube \
#     studio_punch@1.0 warm_shift@0.5 sat_boost@0.7 black_crush@0.5

require_relative 'generate_lut'

color_model = ARGV.delete('--legacy') ? :hsl : DEFAULT_COLOR_MODEL

output_path = ARGV.shift || abort("Usage: ruby generate_chain_lut.rb <output> <preset@strength> ... [--legacy]")

chain = ARGV.map do |arg|
  name, strength = arg.split('@')
  strength = (strength || '1.0').to_f
  preset = load_preset(name)
  { name: name, strength: strength, pipeline: preset['pipeline'], title: preset['title'] }
end

abort("No presets specified") if chain.empty?

title = chain.map { |c| "#{c[:name]}@#{c[:strength]}" }.join(' + ')
comments = [
  "Baked chain LUT: #{title}",
  "Generated by generate_chain_lut.rb",
  "Color model: #{color_model == :linear ? 'linear-light tone (v2)' : 'legacy HSL tone (v1)'}",
] + chain.map { |c| "  #{c[:name]} (#{c[:title]}) @ #{c[:strength]}" }

size = 33

puts "Generating baked chain LUT..."
chain.each { |c| puts "  #{c[:name]} @ #{c[:strength]}" }

table = generate_lut(size) do |r, g, b|
  chain.each do |c|
    r, g, b = apply_pipeline(r, g, b, c[:pipeline], c[:strength], color_model: color_model)
  end
  [r, g, b]
end

write_cube(output_path, table, size, title, comments)
puts "Generated: #{output_path} (#{size}x#{size}x#{size})"
