#!/usr/bin/env ruby
# regenerate_luts.rb - Rebuild every shipped LUT in correction_luts/
#
# The recipes live in correction_luts/manifest.yml, so the shipped .cube files
# are reproducible artifacts rather than hand-made ones. test_luts.rb verifies
# that what is committed matches what this script produces.
#
# Usage:
#   ruby regenerate_luts.rb            # rebuild with the current tone model
#   ruby regenerate_luts.rb --legacy   # rebuild with the v1 HSL tone model
#   ruby regenerate_luts.rb --check    # report drift without writing anything

require 'digest'
require_relative 'generate_lut'

LUT_DIR = File.join(__dir__, 'correction_luts')
MANIFEST_PATH = File.join(LUT_DIR, 'manifest.yml')

color_model = ARGV.include?('--legacy') ? :hsl : DEFAULT_COLOR_MODEL
check_only = ARGV.include?('--check')

manifest = YAML.load_file(MANIFEST_PATH)
model_note = color_model == :linear ? 'linear-light tone (v2)' : 'legacy HSL tone (v1)'

# Build the .cube body for one manifest entry. Returns [table, title, comments].
def build(entry, color_model, model_note)
  if entry['chain']
    steps = entry['chain'].map do |c|
      preset = load_preset(c['preset'])
      { name: c['preset'], strength: c['strength'],
        pipeline: preset['pipeline'], title: preset['title'] }
    end

    title = steps.map { |s| "#{s[:name]}@#{s[:strength]}" }.join(' + ')
    comments = [
      "Baked chain LUT: #{title}",
      "Generated by regenerate_luts.rb",
      "Color model: #{model_note}",
    ] + steps.map { |s| "  #{s[:name]} (#{s[:title]}) @ #{s[:strength]}" }

    table = generate_lut(LUT_DEFAULT_SIZE) do |r, g, b|
      steps.each do |s|
        r, g, b = apply_pipeline(r, g, b, s[:pipeline], s[:strength],
                                 color_model: color_model)
      end
      [r, g, b]
    end
  else
    preset = load_preset(entry['preset'])
    strength = entry['strength']
    title = preset['title']
    comments = (preset['comments'] || []) +
               ["Strength: #{strength}", "Color model: #{model_note}"]

    table = generate_lut(LUT_DEFAULT_SIZE) do |r, g, b|
      apply_pipeline(r, g, b, preset['pipeline'], strength, color_model: color_model)
    end
  end

  [table, title, comments]
end

def data_digest(path)
  Digest::SHA256.hexdigest(File.readlines(path).select { |l| l =~ /^\d/ }.join)
end

drifted = []
manifest.sort.each do |name, entry|
  table, title, comments = build(entry, color_model, model_note)
  path = File.join(LUT_DIR, "#{name}.cube")

  if check_only
    unless File.exist?(path)
      drifted << "#{name} (missing)"
      next
    end
    require 'tempfile'
    Tempfile.create([name, '.cube']) do |tmp|
      write_cube(tmp.path, table, LUT_DEFAULT_SIZE, title, comments)
      drifted << name if data_digest(tmp.path) != data_digest(path)
    end
  else
    write_cube(path, table, LUT_DEFAULT_SIZE, title, comments)
    puts "  #{name}.cube"
  end
end

if check_only
  if drifted.empty?
    puts "All #{manifest.length} shipped LUTs match the manifest (#{model_note})."
  else
    warn "Drift in #{drifted.length} LUT(s): #{drifted.join(', ')}"
    warn "Rebuild with: ruby regenerate_luts.rb"
    exit 1
  end
else
  puts "\nRegenerated #{manifest.length} LUTs using #{model_note}."
end
